services:
  web:
    build: .
    image: brightmetrics-web:latest
    container_name: brightmetrics-web
    isolation: hyperv
    ports:
      - "8008:8008"
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    restart: unless-stopped
    depends_on:
      azurite:
        condition: service_started

  azurite:
    build:
      context: .
      dockerfile: azurite.Dockerfile
    image: brightmetrics-azurite:latest
    isolation: hyperv
    network_mode: "service:web"
    restart: unless-stopped
